MONGODB_HOST: mongodb-{{ env }}.ahay.space # mongodb-dev.ahay.space
REDIS_HOST: redis-{{ env }}.ahay.space
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.ahay.space
CART_HOST: cart.backend-alb-{{ env }}.ahay.space
USER_HOST: user.backend-alb-{{ env }}.ahay.space
RABBITMQ_HOST: rabbitmq-{{ env }}.ahay.space
MYSQL_HOST: mysql-{{ env }}.ahay.space
SHIPPING_HOST: shipping.backend-alb-{{ env }}.ahay.space
PAYMENT_HOST: payment.backend-alb-{{ env }}.ahay.space